# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator/orchestrator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'orchestrator/orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1forchestrator/orchestrator.proto\x12\x0corchestrator\x1a\x1bgoogle/protobuf/empty.proto\"s\n\x0bVectorClock\x12\x35\n\x06values\x18\x01 \x03(\x0b\x32%.orchestrator.VectorClock.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\"6\n\x10\x66raudDoneRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x03\x12\x10\n\x08is_fraud\x18\x02 \x01(\x08\"F\n\x17verificationDoneRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x03\x12\x19\n\x11payment_completed\x18\x02 \x01(\x08\"?\n\x16suggestionsDoneRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x03\x12\x13\n\x0bsuggestions\x18\x02 \x03(\t2\xfe\x01\n\x13OrchestratorService\x12\x43\n\tfraudDone\x12\x1e.orchestrator.fraudDoneRequest\x1a\x16.google.protobuf.Empty\x12Q\n\x10verificationDone\x12%.orchestrator.verificationDoneRequest\x1a\x16.google.protobuf.Empty\x12O\n\x0fsuggestionsDone\x12$.orchestrator.suggestionsDoneRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator.orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORCLOCK_VALUESENTRY']._loaded_options = None
  _globals['_VECTORCLOCK_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_VECTORCLOCK']._serialized_start=78
  _globals['_VECTORCLOCK']._serialized_end=193
  _globals['_VECTORCLOCK_VALUESENTRY']._serialized_start=148
  _globals['_VECTORCLOCK_VALUESENTRY']._serialized_end=193
  _globals['_FRAUDDONEREQUEST']._serialized_start=195
  _globals['_FRAUDDONEREQUEST']._serialized_end=249
  _globals['_VERIFICATIONDONEREQUEST']._serialized_start=251
  _globals['_VERIFICATIONDONEREQUEST']._serialized_end=321
  _globals['_SUGGESTIONSDONEREQUEST']._serialized_start=323
  _globals['_SUGGESTIONSDONEREQUEST']._serialized_end=386
  _globals['_ORCHESTRATORSERVICE']._serialized_start=389
  _globals['_ORCHESTRATORSERVICE']._serialized_end=643
# @@protoc_insertion_point(module_scope)
