# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suggestions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0bsuggestions\"V\n\x10InitOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x1a\n\x12order_payload_json\x18\x02 \x01(\t\x12\x14\n\x0cvector_clock\x18\x03 \x03(\x05\")\n\x11InitOrderResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\"[\n\x1d\x44\x65pendencyNotificationRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\nevent_name\x18\x02 \x01(\t\x12\x14\n\x0cvector_clock\x18\x03 \x03(\x05\x32\xb2\x01\n\x12SuggestionsService\x12J\n\tInitOrder\x12\x1d.suggestions.InitOrderRequest\x1a\x1e.suggestions.InitOrderResponse\x12P\n\x10NotifyECompleted\x12*.suggestions.DependencyNotificationRequest\x1a\x10.suggestions.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITORDERREQUEST']._serialized_start=34
  _globals['_INITORDERREQUEST']._serialized_end=120
  _globals['_INITORDERRESPONSE']._serialized_start=122
  _globals['_INITORDERRESPONSE']._serialized_end=163
  _globals['_ACK']._serialized_start=165
  _globals['_ACK']._serialized_end=182
  _globals['_DEPENDENCYNOTIFICATIONREQUEST']._serialized_start=184
  _globals['_DEPENDENCYNOTIFICATIONREQUEST']._serialized_end=275
  _globals['_SUGGESTIONSSERVICE']._serialized_start=278
  _globals['_SUGGESTIONSSERVICE']._serialized_end=456
# @@protoc_insertion_point(module_scope)
