# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from utils.pb.suggestions import suggestions_pb2 as utils_dot_pb_dot_suggestions_dot_suggestions__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in utils/pb/suggestions/suggestions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SuggestionsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSuggestions = channel.unary_unary(
                '/suggestions.SuggestionsService/GetSuggestions',
                request_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.SuggestionsRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.SuggestionsResponse.FromString,
                _registered_method=True)
        self.TriggerSuggestions = channel.unary_unary(
                '/suggestions.SuggestionsService/TriggerSuggestions',
                request_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.TriggerRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.SuggestionsResponse.FromString,
                _registered_method=True)
        self.GetVectorClock = channel.unary_unary(
                '/suggestions.SuggestionsService/GetVectorClock',
                request_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.VectorClockRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.VectorClockResponse.FromString,
                _registered_method=True)
        self.ClearOrder = channel.unary_unary(
                '/suggestions.SuggestionsService/ClearOrder',
                request_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.ClearOrderRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.ClearOrderResponse.FromString,
                _registered_method=True)


class SuggestionsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSuggestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerSuggestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVectorClock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSuggestions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSuggestions,
                    request_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.SuggestionsRequest.FromString,
                    response_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.SuggestionsResponse.SerializeToString,
            ),
            'TriggerSuggestions': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerSuggestions,
                    request_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.TriggerRequest.FromString,
                    response_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.SuggestionsResponse.SerializeToString,
            ),
            'GetVectorClock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVectorClock,
                    request_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.VectorClockRequest.FromString,
                    response_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.VectorClockResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.ClearOrderRequest.FromString,
                    response_serializer=utils_dot_pb_dot_suggestions_dot_suggestions__pb2.ClearOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'suggestions.SuggestionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('suggestions.SuggestionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SuggestionsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suggestions.SuggestionsService/GetSuggestions',
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.SuggestionsRequest.SerializeToString,
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.SuggestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suggestions.SuggestionsService/TriggerSuggestions',
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.TriggerRequest.SerializeToString,
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.SuggestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVectorClock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suggestions.SuggestionsService/GetVectorClock',
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.VectorClockRequest.SerializeToString,
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.VectorClockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suggestions.SuggestionsService/ClearOrder',
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.ClearOrderRequest.SerializeToString,
            utils_dot_pb_dot_suggestions_dot_suggestions__pb2.ClearOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
