# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suggestions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0bsuggestions\"\'\n\x0eSuggestRequest\x12\x15\n\rordered_books\x18\x01 \x03(\t\"*\n\x0fSuggestResponse\x12\x17\n\x0fsuggested_books\x18\x01 \x03(\t2Z\n\x12SuggestionsService\x12\x44\n\x07suggest\x12\x1b.suggestions.SuggestRequest\x1a\x1c.suggestions.SuggestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUGGESTREQUEST']._serialized_start=34
  _globals['_SUGGESTREQUEST']._serialized_end=73
  _globals['_SUGGESTRESPONSE']._serialized_start=75
  _globals['_SUGGESTRESPONSE']._serialized_end=117
  _globals['_SUGGESTIONSSERVICE']._serialized_start=119
  _globals['_SUGGESTIONSSERVICE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
