# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import suggestions_pb2 as suggestions__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in suggestions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SuggestionsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitOrder = channel.unary_unary(
                '/suggestions.SuggestionsService/InitOrder',
                request_serializer=suggestions__pb2.InitOrderRequest.SerializeToString,
                response_deserializer=suggestions__pb2.InitOrderResponse.FromString,
                _registered_method=True)
        self.NotifyECompleted = channel.unary_unary(
                '/suggestions.SuggestionsService/NotifyECompleted',
                request_serializer=suggestions__pb2.DependencyNotificationRequest.SerializeToString,
                response_deserializer=suggestions__pb2.Ack.FromString,
                _registered_method=True)
        self.CleanupOrder = channel.unary_unary(
                '/suggestions.SuggestionsService/CleanupOrder',
                request_serializer=suggestions__pb2.CleanupOrderRequest.SerializeToString,
                response_deserializer=suggestions__pb2.CleanupOrderResponse.FromString,
                _registered_method=True)


class SuggestionsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyECompleted(self, request, context):
        """fraud service notifies suggestions service that e completed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupOrder(self, request, context):
        """orchestrator broadcasts final cleanup after checkout flow ends
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=suggestions__pb2.InitOrderRequest.FromString,
                    response_serializer=suggestions__pb2.InitOrderResponse.SerializeToString,
            ),
            'NotifyECompleted': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyECompleted,
                    request_deserializer=suggestions__pb2.DependencyNotificationRequest.FromString,
                    response_serializer=suggestions__pb2.Ack.SerializeToString,
            ),
            'CleanupOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupOrder,
                    request_deserializer=suggestions__pb2.CleanupOrderRequest.FromString,
                    response_serializer=suggestions__pb2.CleanupOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'suggestions.SuggestionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('suggestions.SuggestionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SuggestionsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suggestions.SuggestionsService/InitOrder',
            suggestions__pb2.InitOrderRequest.SerializeToString,
            suggestions__pb2.InitOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyECompleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suggestions.SuggestionsService/NotifyECompleted',
            suggestions__pb2.DependencyNotificationRequest.SerializeToString,
            suggestions__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanupOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suggestions.SuggestionsService/CleanupOrder',
            suggestions__pb2.CleanupOrderRequest.SerializeToString,
            suggestions__pb2.CleanupOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
