# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import order_mq_pb2 as order__mq__pb2


class OrderMqServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/ordermq.OrderMqService/HealthCheck',
                request_serializer=order__mq__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=order__mq__pb2.HealthCheckResponse.FromString,
                )
        self.EnqueueOrder = channel.unary_unary(
                '/ordermq.OrderMqService/EnqueueOrder',
                request_serializer=order__mq__pb2.EnqueueOrderRequest.SerializeToString,
                response_deserializer=order__mq__pb2.EnqueueOrderResponse.FromString,
                )
        self.DequeueOrder = channel.unary_unary(
                '/ordermq.OrderMqService/DequeueOrder',
                request_serializer=order__mq__pb2.DequeueOrderRequest.SerializeToString,
                response_deserializer=order__mq__pb2.DequeueOrderResponse.FromString,
                )


class OrderMqServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DequeueOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderMqServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=order__mq__pb2.HealthCheckRequest.FromString,
                    response_serializer=order__mq__pb2.HealthCheckResponse.SerializeToString,
            ),
            'EnqueueOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueOrder,
                    request_deserializer=order__mq__pb2.EnqueueOrderRequest.FromString,
                    response_serializer=order__mq__pb2.EnqueueOrderResponse.SerializeToString,
            ),
            'DequeueOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.DequeueOrder,
                    request_deserializer=order__mq__pb2.DequeueOrderRequest.FromString,
                    response_serializer=order__mq__pb2.DequeueOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ordermq.OrderMqService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderMqService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ordermq.OrderMqService/HealthCheck',
            order__mq__pb2.HealthCheckRequest.SerializeToString,
            order__mq__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnqueueOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ordermq.OrderMqService/EnqueueOrder',
            order__mq__pb2.EnqueueOrderRequest.SerializeToString,
            order__mq__pb2.EnqueueOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DequeueOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ordermq.OrderMqService/DequeueOrder',
            order__mq__pb2.DequeueOrderRequest.SerializeToString,
            order__mq__pb2.DequeueOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
