# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_mq.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eorder_mq.proto\x12\x07ordermq\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\";\n\x13\x45nqueueOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\norder_data\x18\x02 \x01(\t\"&\n\x14\x45nqueueOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x15\n\x13\x44\x65queueOrderRequest\"<\n\x14\x44\x65queueOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\norder_data\x18\x02 \x01(\t2\xf4\x01\n\x0eOrderMqService\x12H\n\x0bHealthCheck\x12\x1b.ordermq.HealthCheckRequest\x1a\x1c.ordermq.HealthCheckResponse\x12K\n\x0c\x45nqueueOrder\x12\x1c.ordermq.EnqueueOrderRequest\x1a\x1d.ordermq.EnqueueOrderResponse\x12K\n\x0c\x44\x65queueOrder\x12\x1c.ordermq.DequeueOrderRequest\x1a\x1d.ordermq.DequeueOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_mq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=27
  _globals['_HEALTHCHECKREQUEST']._serialized_end=47
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=49
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=86
  _globals['_ENQUEUEORDERREQUEST']._serialized_start=88
  _globals['_ENQUEUEORDERREQUEST']._serialized_end=147
  _globals['_ENQUEUEORDERRESPONSE']._serialized_start=149
  _globals['_ENQUEUEORDERRESPONSE']._serialized_end=187
  _globals['_DEQUEUEORDERREQUEST']._serialized_start=189
  _globals['_DEQUEUEORDERREQUEST']._serialized_end=210
  _globals['_DEQUEUEORDERRESPONSE']._serialized_start=212
  _globals['_DEQUEUEORDERRESPONSE']._serialized_end=272
  _globals['_ORDERMQSERVICE']._serialized_start=275
  _globals['_ORDERMQSERVICE']._serialized_end=519
# @@protoc_insertion_point(module_scope)
