# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mq.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08mq.proto\x12\x02mq\"G\n\x0f\x43heckoutRequest\x12\x10\n\x08priority\x18\x01 \x01(\x05\x12\"\n\ncreditcard\x18\x03 \x01(\x0b\x32\x0e.mq.CreditCard\"A\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"0\n\x08Response\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2d\n\tMQService\x12,\n\x07\x65nqueue\x12\x13.mq.CheckoutRequest\x1a\x0c.mq.Response\x12)\n\x07\x64\x65queue\x12\t.mq.Empty\x1a\x13.mq.CheckoutRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECKOUTREQUEST']._serialized_start=16
  _globals['_CHECKOUTREQUEST']._serialized_end=87
  _globals['_CREDITCARD']._serialized_start=89
  _globals['_CREDITCARD']._serialized_end=154
  _globals['_RESPONSE']._serialized_start=156
  _globals['_RESPONSE']._serialized_end=204
  _globals['_EMPTY']._serialized_start=206
  _globals['_EMPTY']._serialized_end=213
  _globals['_MQSERVICE']._serialized_start=215
  _globals['_MQSERVICE']._serialized_end=315
# @@protoc_insertion_point(module_scope)
