services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
  orchestrator:
    build:
      context: ./
      dockerfile: ./orchestrator/Dockerfile
    ports:
      - 8081:5000
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/orchestrator/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./orchestrator/src:/app/orchestrator/src
  fraud_detection:
    build:
      context: ./
      dockerfile: ./fraud_detection/Dockerfile
    ports:
      - 50051:50051
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/fraud_detection/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./fraud_detection/src:/app/fraud_detection/src
  transaction_verification:
    build:
      context: ./
      dockerfile: ./transaction_verification/Dockerfile
    ports:
      - 50052:50052
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/transaction_verification/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./transaction_verification/src:/app/transaction_verification/src
