services:
  frontend:
    build:
      context: ./
      dockerfile: ./services/frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./services/frontend/src:/usr/share/nginx/html
  orchestrator:
    build:
      context: ./
      dockerfile: ./services/orchestrator/Dockerfile
    ports:
      - 8081:5000
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/services/orchestrator/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./services/orchestrator/src:/app/services/orchestrator/src
      - ./services/orchestrator/tests:/app/services/orchestrator/tests
  fraud_detection:
    build:
      context: ./
      dockerfile: ./services/fraud_detection/Dockerfile
    ports:
      - 50051:50051
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/services/fraud_detection/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./services/fraud_detection/src:/app/services/fraud_detection/src
      - ./services/fraud_detection/tests:/app/services/fraud_detection/tests
  transaction_verification:
    build:
      context: ./
      dockerfile: ./services/transaction_verification/Dockerfile
    ports:
      - 50052:50052
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/services/transaction_verification/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./services/transaction_verification/src:/app/services/transaction_verification/src
      - ./services/transaction_verification/tests:/app/services/transaction_verification/tests
  suggestions:
    build:
      context: ./
      dockerfile: ./services/suggestions/Dockerfile
    ports:
      - 50053:50053
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/services/suggestions/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./services/suggestions/src:/app/services/suggestions/src
      - ./services/suggestions/tests:/app/services/suggestions/tests
