# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import utils.pb.payment_service.payment_service_pb2 as  payment__service__pb2 


class Payment_ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Request_Commit = channel.unary_unary(
                '/payment_service.Payment_Service/Request_Commit',
                request_serializer=payment__service__pb2.Request_Commit_Message.SerializeToString,
                response_deserializer=payment__service__pb2.Response.FromString,
                )
        self.Commit = channel.unary_unary(
                '/payment_service.Payment_Service/Commit',
                request_serializer=payment__service__pb2.Commit_Message.SerializeToString,
                response_deserializer=payment__service__pb2.Response.FromString,
                )


class Payment_ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Request_Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Payment_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Request_Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Request_Commit,
                    request_deserializer=payment__service__pb2.Request_Commit_Message.FromString,
                    response_serializer=payment__service__pb2.Response.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=payment__service__pb2.Commit_Message.FromString,
                    response_serializer=payment__service__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment_service.Payment_Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Payment_Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Request_Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment_service.Payment_Service/Request_Commit',
            payment__service__pb2.Request_Commit_Message.SerializeToString,
            payment__service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment_service.Payment_Service/Commit',
            payment__service__pb2.Commit_Message.SerializeToString,
            payment__service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
