# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fraud_detection_pb2 as fraud__detection__pb2


class FraudDetectionServiceStub(object):
    """Our new gRPC service name
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckOrder = channel.unary_unary(
                '/fraud.FraudDetectionService/CheckOrder',
                request_serializer=fraud__detection__pb2.CheckOrderRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.CheckOrderResponse.FromString,
                )


class FraudDetectionServiceServicer(object):
    """Our new gRPC service name
    """

    def CheckOrder(self, request, context):
        """The method the Orchestrator will call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOrder,
                    request_deserializer=fraud__detection__pb2.CheckOrderRequest.FromString,
                    response_serializer=fraud__detection__pb2.CheckOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud.FraudDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FraudDetectionService(object):
    """Our new gRPC service name
    """

    @staticmethod
    def CheckOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud.FraudDetectionService/CheckOrder',
            fraud__detection__pb2.CheckOrderRequest.SerializeToString,
            fraud__detection__pb2.CheckOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
