# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from utils.pb.fraud_detection import fraud_detection_pb2 as utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2


class HelloServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/hello.HelloService/SayHello',
                request_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.HelloRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.HelloResponse.FromString,
                )


class HelloServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.HelloRequest.FromString,
                    response_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.HelloResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello.HelloService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HelloService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.HelloService/SayHello',
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.HelloRequest.SerializeToString,
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.HelloResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class OrderIdStorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StorageOrderId = channel.unary_unary(
                '/hello.OrderIdStorageService/StorageOrderId',
                request_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.OrderIdStorageRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.OrderIdStorageResponse.FromString,
                )


class OrderIdStorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StorageOrderId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderIdStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StorageOrderId': grpc.unary_unary_rpc_method_handler(
                    servicer.StorageOrderId,
                    request_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.OrderIdStorageRequest.FromString,
                    response_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.OrderIdStorageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello.OrderIdStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderIdStorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StorageOrderId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.OrderIdStorageService/StorageOrderId',
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.OrderIdStorageRequest.SerializeToString,
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.OrderIdStorageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class UserdataFraudDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectUserdataFraud = channel.unary_unary(
                '/hello.UserdataFraudDetectionService/DetectUserdataFraud',
                request_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.UserdataFraudDetectionRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.UserdataFraudDetectionResponse.FromString,
                )


class UserdataFraudDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectUserdataFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserdataFraudDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectUserdataFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectUserdataFraud,
                    request_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.UserdataFraudDetectionRequest.FromString,
                    response_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.UserdataFraudDetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello.UserdataFraudDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserdataFraudDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectUserdataFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.UserdataFraudDetectionService/DetectUserdataFraud',
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.UserdataFraudDetectionRequest.SerializeToString,
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.UserdataFraudDetectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class CardinfoFraudDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectCardinfoFraud = channel.unary_unary(
                '/hello.CardinfoFraudDetectionService/DetectCardinfoFraud',
                request_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.CardinfoFraudDetectionRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.CardinfoFraudDetectionResponse.FromString,
                )


class CardinfoFraudDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectCardinfoFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CardinfoFraudDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectCardinfoFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectCardinfoFraud,
                    request_deserializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.CardinfoFraudDetectionRequest.FromString,
                    response_serializer=utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.CardinfoFraudDetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello.CardinfoFraudDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CardinfoFraudDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectCardinfoFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.CardinfoFraudDetectionService/DetectCardinfoFraud',
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.CardinfoFraudDetectionRequest.SerializeToString,
            utils_dot_pb_dot_fraud__detection_dot_fraud__detection__pb2.CardinfoFraudDetectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
