# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"\x1d\n\x0bVectorClock\x12\x0e\n\x06values\x18\x01 \x03(\x05\"\xad\x01\n\tOrderData\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x14\n\x0cuser_contact\x18\x03 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x04 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x05 \x01(\t\x12\x0b\n\x03\x63vv\x18\x06 \x01(\t\x12\x12\n\nitem_count\x18\x07 \x01(\x05\x12\x16\n\x0eterms_accepted\x18\x08 \x01(\x08\"=\n\x10InitOrderRequest\x12)\n\x05order\x18\x01 \x01(\x0b\x32\x1a.fraud_detection.OrderData\"J\n\x0c\x45ventRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12(\n\x02vc\x18\x02 \x01(\x0b\x32\x1c.fraud_detection.VectorClock\"[\n\rEventResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12(\n\x02vc\x18\x03 \x01(\x0b\x32\x1c.fraud_detection.VectorClock\"U\n\x11\x43learOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12.\n\x08\x66inal_vc\x18\x02 \x01(\x0b\x32\x1c.fraud_detection.VectorClock2\xdb\x02\n\x15\x46raudDetectionService\x12N\n\tInitOrder\x12!.fraud_detection.InitOrderRequest\x1a\x1e.fraud_detection.EventResponse\x12O\n\x0e\x43heckUserFraud\x12\x1d.fraud_detection.EventRequest\x1a\x1e.fraud_detection.EventResponse\x12O\n\x0e\x43heckCardFraud\x12\x1d.fraud_detection.EventRequest\x1a\x1e.fraud_detection.EventResponse\x12P\n\nClearOrder\x12\".fraud_detection.ClearOrderRequest\x1a\x1e.fraud_detection.EventResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORCLOCK']._serialized_start=42
  _globals['_VECTORCLOCK']._serialized_end=71
  _globals['_ORDERDATA']._serialized_start=74
  _globals['_ORDERDATA']._serialized_end=247
  _globals['_INITORDERREQUEST']._serialized_start=249
  _globals['_INITORDERREQUEST']._serialized_end=310
  _globals['_EVENTREQUEST']._serialized_start=312
  _globals['_EVENTREQUEST']._serialized_end=386
  _globals['_EVENTRESPONSE']._serialized_start=388
  _globals['_EVENTRESPONSE']._serialized_end=479
  _globals['_CLEARORDERREQUEST']._serialized_start=481
  _globals['_CLEARORDERREQUEST']._serialized_end=566
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=569
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=916
# @@protoc_insertion_point(module_scope)
