# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\tbookstore\"\xad\x02\n\tOrderInfo\x12\x1d\n\x04user\x18\x01 \x01(\x0b\x32\x0f.bookstore.User\x12)\n\ncreditCard\x18\x02 \x01(\x0b\x32\x15.bookstore.CreditCard\x12\x13\n\x0buserComment\x18\x03 \x01(\t\x12#\n\x05items\x18\x04 \x03(\x0b\x32\x14.bookstore.OrderItem\x12*\n\x0e\x62illingAddress\x18\x05 \x01(\x0b\x32\x12.bookstore.Address\x12+\n\x0fshippingAddress\x18\x06 \x01(\x0b\x32\x12.bookstore.Address\x12\x16\n\x0eshippingMethod\x18\x07 \x01(\t\x12\x14\n\x0cgiftWrapping\x18\x08 \x01(\x08\x12\x15\n\rtermsAccepted\x18\t \x01(\x08\"=\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\x12\x16\n\x0e\x63\x61rdHolderName\x18\x03 \x01(\t\"A\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"+\n\tOrderItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"8\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\">\n\x16\x46raudDetectionResponse\x12\x14\n\x0cisFraudulent\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2c\n\x15\x46raudDetectionService\x12J\n\x0f\x44\x65tectUserFraud\x12\x14.bookstore.OrderInfo\x1a!.bookstore.FraudDetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERINFO']._serialized_start=37
  _globals['_ORDERINFO']._serialized_end=338
  _globals['_USER']._serialized_start=340
  _globals['_USER']._serialized_end=401
  _globals['_CREDITCARD']._serialized_start=403
  _globals['_CREDITCARD']._serialized_end=468
  _globals['_ORDERITEM']._serialized_start=470
  _globals['_ORDERITEM']._serialized_end=513
  _globals['_ADDRESS']._serialized_start=515
  _globals['_ADDRESS']._serialized_end=571
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=573
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=635
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=637
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=736
# @@protoc_insertion_point(module_scope)
