# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"\x16\n\x14\x41ppendEntriesRequest\"\x17\n\x15\x41ppendEntriesResponse\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"4\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07granted\x18\x02 \x01(\x08\")\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t2\x98\x01\n\x04Raft\x12J\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\"\x00\x12\x44\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APPENDENTRIESREQUEST']._serialized_start=20
  _globals['_APPENDENTRIESREQUEST']._serialized_end=42
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=44
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=67
  _globals['_REQUESTVOTEREQUEST']._serialized_start=69
  _globals['_REQUESTVOTEREQUEST']._serialized_end=172
  _globals['_REQUESTVOTERESPONSE']._serialized_start=174
  _globals['_REQUESTVOTERESPONSE']._serialized_end=226
  _globals['_LOGENTRY']._serialized_start=228
  _globals['_LOGENTRY']._serialized_end=269
  _globals['_RAFT']._serialized_start=272
  _globals['_RAFT']._serialized_end=424
# @@protoc_insertion_point(module_scope)
