# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_queue.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'order_queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order_queue.proto\x12\x0border_queue\"\xad\x01\n\tOrderData\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x14\n\x0cuser_contact\x18\x03 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x04 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x05 \x01(\t\x12\x0b\n\x03\x63vv\x18\x06 \x01(\t\x12\x12\n\nitem_count\x18\x07 \x01(\x05\x12\x16\n\x0eterms_accepted\x18\x08 \x01(\x08\"7\n\x0e\x45nqueueRequest\x12%\n\x05order\x18\x01 \x01(\x0b\x32\x16.order_queue.OrderData\"%\n\x0e\x44\x65queueRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\"1\n\rQueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"Z\n\x0f\x44\x65queueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12%\n\x05order\x18\x03 \x01(\x0b\x32\x16.order_queue.OrderData2\x9d\x01\n\x11OrderQueueService\x12\x42\n\x07\x45nqueue\x12\x1b.order_queue.EnqueueRequest\x1a\x1a.order_queue.QueueResponse\x12\x44\n\x07\x44\x65queue\x12\x1b.order_queue.DequeueRequest\x1a\x1c.order_queue.DequeueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERDATA']._serialized_start=35
  _globals['_ORDERDATA']._serialized_end=208
  _globals['_ENQUEUEREQUEST']._serialized_start=210
  _globals['_ENQUEUEREQUEST']._serialized_end=265
  _globals['_DEQUEUEREQUEST']._serialized_start=267
  _globals['_DEQUEUEREQUEST']._serialized_end=304
  _globals['_QUEUERESPONSE']._serialized_start=306
  _globals['_QUEUERESPONSE']._serialized_end=355
  _globals['_DEQUEUERESPONSE']._serialized_start=357
  _globals['_DEQUEUERESPONSE']._serialized_end=447
  _globals['_ORDERQUEUESERVICE']._serialized_start=450
  _globals['_ORDERQUEUESERVICE']._serialized_end=607
# @@protoc_insertion_point(module_scope)
