# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/order_queue/order_queue.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/order_queue/order_queue.proto\x1a\x1bgoogle/protobuf/empty.proto\"+\n\tOrderItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"]\n\tOrderData\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x19\n\x05items\x18\x02 \x03(\x0b\x32\n.OrderItem\x12\x10\n\x08userData\x18\x03 \x01(\t\x12\x12\n\ncreditCard\x18\x04 \x01(\t\"*\n\rOptionalOrder\x12\x19\n\x05order\x18\x01 \x01(\x0b\x32\n.OrderData2\x7f\n\x11OrderQueueService\x12\x32\n\x0c\x45nqueueOrder\x12\n.OrderData\x1a\x16.google.protobuf.Empty\x12\x36\n\x0c\x44\x65queueOrder\x12\x16.google.protobuf.Empty\x1a\x0e.OptionalOrderb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_queue.order_queue_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDERITEM._serialized_start=71
  _ORDERITEM._serialized_end=114
  _ORDERDATA._serialized_start=116
  _ORDERDATA._serialized_end=209
  _OPTIONALORDER._serialized_start=211
  _OPTIONALORDER._serialized_end=253
  _ORDERQUEUESERVICE._serialized_start=255
  _ORDERQUEUESERVICE._serialized_end=382
# @@protoc_insertion_point(module_scope)
