# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/order_queue/order_queue.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/order_queue/order_queue.proto\x12\x0border_queue\"%\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"A\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"\xc8\x01\n\x05Order\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x1f\n\x04user\x18\x02 \x01(\x0b\x32\x11.order_queue.User\x12 \n\x05items\x18\x03 \x03(\x0b\x32\x11.order_queue.Item\x12+\n\ncreditCard\x18\x04 \x01(\x0b\x32\x17.order_queue.CreditCard\x12,\n\x07\x61\x64\x64ress\x18\x05 \x01(\x0b\x32\x1b.order_queue.BillingAddress\x12\x10\n\x08priority\x18\x06 \x01(\x05\"[\n\x0e\x42illingAddress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"3\n\x0e\x45nqueueRequest\x12!\n\x05order\x18\x01 \x01(\x0b\x32\x12.order_queue.Order\"\"\n\x0f\x45nqueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x10\n\x0e\x44\x65queueRequest\"E\n\x0f\x44\x65queueResponse\x12!\n\x05order\x18\x01 \x01(\x0b\x32\x12.order_queue.Order\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x9f\x01\n\x11OrderQueueService\x12\x44\n\x07\x45nqueue\x12\x1b.order_queue.EnqueueRequest\x1a\x1c.order_queue.EnqueueResponse\x12\x44\n\x07\x44\x65queue\x12\x1b.order_queue.DequeueRequest\x1a\x1c.order_queue.DequeueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_queue.order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=55
  _globals['_USER']._serialized_end=92
  _globals['_ITEM']._serialized_start=94
  _globals['_ITEM']._serialized_end=132
  _globals['_CREDITCARD']._serialized_start=134
  _globals['_CREDITCARD']._serialized_end=199
  _globals['_ORDER']._serialized_start=202
  _globals['_ORDER']._serialized_end=402
  _globals['_BILLINGADDRESS']._serialized_start=404
  _globals['_BILLINGADDRESS']._serialized_end=495
  _globals['_ENQUEUEREQUEST']._serialized_start=497
  _globals['_ENQUEUEREQUEST']._serialized_end=548
  _globals['_ENQUEUERESPONSE']._serialized_start=550
  _globals['_ENQUEUERESPONSE']._serialized_end=584
  _globals['_DEQUEUEREQUEST']._serialized_start=586
  _globals['_DEQUEUEREQUEST']._serialized_end=602
  _globals['_DEQUEUERESPONSE']._serialized_start=604
  _globals['_DEQUEUERESPONSE']._serialized_end=673
  _globals['_ORDERQUEUESERVICE']._serialized_start=676
  _globals['_ORDERQUEUESERVICE']._serialized_end=835
# @@protoc_insertion_point(module_scope)
