# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suggestions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\tbookstore\" \n\x0b\x42ookRequest\x12\x11\n\tbook_name\x18\x01 \x01(\t\"B\n\x13SuggestionsResponse\x12+\n\x0bsuggestions\x18\x01 \x03(\x0b\x32\x16.bookstore.Suggestions\"6\n\x0bSuggestions\x12\x12\n\nbook_title\x18\x01 \x01(\t\x12\x13\n\x0b\x62ook_author\x18\x02 \x01(\t2\\\n\x12SuggestionsService\x12\x46\n\x0cSuggestBooks\x12\x16.bookstore.BookRequest\x1a\x1e.bookstore.SuggestionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKREQUEST']._serialized_start=32
  _globals['_BOOKREQUEST']._serialized_end=64
  _globals['_SUGGESTIONSRESPONSE']._serialized_start=66
  _globals['_SUGGESTIONSRESPONSE']._serialized_end=132
  _globals['_SUGGESTIONS']._serialized_start=134
  _globals['_SUGGESTIONS']._serialized_end=188
  _globals['_SUGGESTIONSSERVICE']._serialized_start=190
  _globals['_SUGGESTIONSSERVICE']._serialized_end=282
# @@protoc_insertion_point(module_scope)
