# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import transaction_verification_pb2 as transaction__verification__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in transaction_verification_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransactionVerificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitOrder = channel.unary_unary(
                '/transaction.TransactionVerificationService/InitOrder',
                request_serializer=transaction__verification__pb2.InitOrderRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.InitOrderResponse.FromString,
                _registered_method=True)
        self.StartCheckoutFlow = channel.unary_unary(
                '/transaction.TransactionVerificationService/StartCheckoutFlow',
                request_serializer=transaction__verification__pb2.StartCheckoutFlowRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.StartCheckoutFlowResponse.FromString,
                _registered_method=True)
        self.FinalizeOrder = channel.unary_unary(
                '/transaction.TransactionVerificationService/FinalizeOrder',
                request_serializer=transaction__verification__pb2.FinalizeOrderRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.Ack.FromString,
                _registered_method=True)


class TransactionVerificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCheckoutFlow(self, request, context):
        """Orchestrator starts the whole workflow here
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeOrder(self, request, context):
        """Final result is reported back here
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionVerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=transaction__verification__pb2.InitOrderRequest.FromString,
                    response_serializer=transaction__verification__pb2.InitOrderResponse.SerializeToString,
            ),
            'StartCheckoutFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCheckoutFlow,
                    request_deserializer=transaction__verification__pb2.StartCheckoutFlowRequest.FromString,
                    response_serializer=transaction__verification__pb2.StartCheckoutFlowResponse.SerializeToString,
            ),
            'FinalizeOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeOrder,
                    request_deserializer=transaction__verification__pb2.FinalizeOrderRequest.FromString,
                    response_serializer=transaction__verification__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction.TransactionVerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transaction.TransactionVerificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransactionVerificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction.TransactionVerificationService/InitOrder',
            transaction__verification__pb2.InitOrderRequest.SerializeToString,
            transaction__verification__pb2.InitOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartCheckoutFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction.TransactionVerificationService/StartCheckoutFlow',
            transaction__verification__pb2.StartCheckoutFlowRequest.SerializeToString,
            transaction__verification__pb2.StartCheckoutFlowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction.TransactionVerificationService/FinalizeOrder',
            transaction__verification__pb2.FinalizeOrderRequest.SerializeToString,
            transaction__verification__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
