# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x0btransaction\"+\n\x12TransactionRequest\x12\x15\n\rtransactionId\x18\x01 \x01(\t\"\x15\n\x13TransactionResponse\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xbe\x01\n\x12TransactionService\x12V\n\x11VerifyTransaction\x12\x1f.transaction.TransactionRequest\x1a .transaction.TransactionResponse\x12P\n\x0bHealthCheck\x12\x1f.transaction.HealthCheckRequest\x1a .transaction.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=47
  _globals['_TRANSACTIONREQUEST']._serialized_end=90
  _globals['_TRANSACTIONRESPONSE']._serialized_start=92
  _globals['_TRANSACTIONRESPONSE']._serialized_end=113
  _globals['_HEALTHCHECKREQUEST']._serialized_start=115
  _globals['_HEALTHCHECKREQUEST']._serialized_end=135
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=137
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=174
  _globals['_TRANSACTIONSERVICE']._serialized_start=177
  _globals['_TRANSACTIONSERVICE']._serialized_end=367
# @@protoc_insertion_point(module_scope)
