# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_executor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'order_executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\x0eorder_executor\"\'\n\x0f\x45lectionRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\x05\"!\n\x10\x45lectionResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\"\'\n\x12\x43oordinatorRequest\x12\x11\n\tleader_id\x18\x01 \x01(\x05\"%\n\x10HeartbeatRequest\x12\x11\n\tleader_id\x18\x01 \x01(\x05\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xf1\x01\n\x14OrderExecutorControl\x12M\n\x08\x45lection\x12\x1f.order_executor.ElectionRequest\x1a .order_executor.ElectionResponse\x12\x46\n\x0b\x43oordinator\x12\".order_executor.CoordinatorRequest\x1a\x13.order_executor.Ack\x12\x42\n\tHeartbeat\x12 .order_executor.HeartbeatRequest\x1a\x13.order_executor.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONREQUEST']._serialized_start=40
  _globals['_ELECTIONREQUEST']._serialized_end=79
  _globals['_ELECTIONRESPONSE']._serialized_start=81
  _globals['_ELECTIONRESPONSE']._serialized_end=114
  _globals['_COORDINATORREQUEST']._serialized_start=116
  _globals['_COORDINATORREQUEST']._serialized_end=155
  _globals['_HEARTBEATREQUEST']._serialized_start=157
  _globals['_HEARTBEATREQUEST']._serialized_end=194
  _globals['_ACK']._serialized_start=196
  _globals['_ACK']._serialized_end=213
  _globals['_ORDEREXECUTORCONTROL']._serialized_start=216
  _globals['_ORDEREXECUTORCONTROL']._serialized_end=457
# @@protoc_insertion_point(module_scope)
